spring.application.name=backend
spring.jackson.mapper.accept-case-insensitive-properties=true
ml.service.url=${ML_SERVICE_URL:http://localhost:8000/predict}

# Database connection
spring.datasource.url=jdbc:h2:file:./data/frauddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Hibernate automatically create/update tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console